name: MultiMM

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out your repository
    
    # Set up Python 3.10 for the environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Install dependencies needed for the build and environment setup
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  # Needed to build the package
        pip install .  # Install the MultiMM package from the current directory

    # Build the package (wheel + source distribution)
    - name: Build package
      run: python -m build

    # Use PyPI token
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verify_metadata: false
        skip_existing: true

    # Set up the environment to run MultiMM - example run
    - name: Test MultiMM command
      run: |
        MultiMM -c config.ini  # Run MultiMM with a sample config file
